blank_issues_enabled: true
contact_links:
  - name: Conheça o TIME
    url: https://github.com/orgs/sec365br/projects/1/views/1?pane=issue&itemId=110118069&issue=sec365br%7Cproman%7C1
    about: Time da SEC365
