name: Atividade SEC365
description: Atribua o trabalho
title: "[AT] "
labels: ["Atividade", "🎯 Prioridade Média", "⏱️ Tamanho Estimado"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reservar um tempo para atribuir este trabalho!
  - type: textarea
    attributes:
      label: Qual é o objetivo desta tarefa?
      description: Explique claramente o propósito da atividade e os critérios de avaliação.
    validations:
      required: true
  - type: input
    attributes:
      label: Tempo estimado em horas
      description: Quantas horas o participante deverá investir?
    validations:
      required: true
  - type: input
    attributes:
      label: Link da tarefa
      description: Informe o link relacionado a esta atividade.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Como enviar
      description: Indique os passos necessários para submissão da tarefa.
      placeholder: |
        1. Acesse o link da atividade
        2. Realize as etapas propostas
        3. Envie o resultado conforme indicado
    validations:
      required: false
  - type: textarea
    attributes:
      label: Outras informações
      description: |
        Links, referências ou qualquer material complementar que ajude a contextualizar a tarefa.
        Dica: Você pode anexar imagens ou arquivos arrastando-os para esta área.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        **Muito obrigado.**

        Agora, por favor, conclua este ticket preenchendo as opções na barra lateral:

        1. Atualize os rótulos (labels)
        - Prioridade – este item é essencial, obrigatório ou opcional?
        - Tamanho – ajude os participantes a estimar o esforço necessário

        2. Adicione a um marco (milestone)
        - Semana 1, 2, 3 ou 4

        3. Adicione ao backlog do projeto
        - Relacione ao projeto com o mesmo nome deste repositório
        - Preencha os campos personalizados – prioridade, tamanho, horas – de acordo com esta issue
