name: Atividade
description: Atribua o Trabalho
title: "[AT]- "
labels: [Prioridade]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reservar um tempo para atribuir este trabalho!
  - type: input
    attributes:
      label: Link
    validations:
      required: true
  - type: input
    attributes:
      label: Tempo estimado em horas:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Qual é o objetivo desta tarefa?
      description: Explique claramente o propósito desta tarefa e como será avaliado.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Como enviar
      description: Explique em etapas claras como pode ser enviada esta tarefa.
      placeholder: |
        1: 
        2: 
        3:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Outras Informações:
      description: |
        Possui links, referências ou outros materiais que ajudem a entender melhor o contexto?
        Você pode anexar imagens, logs ou qualquer outro arquivo relevante clicando nesta área ou arrastando os arquivos diretamente aqui.
  - type: markdown
    attributes:
      value: |
        **Thank you so much.**

        Please now complete this ticket by filling in the options on the sidebar.

        1. Update labels
        - priority -- is this coursework key, mandatory, or stretch?
        - size -- help trainees plan their time with rough estimation
        2. Add to milestone
        - week 1,2,3,4
        3. Add to project backlog
        - add to the project named the same as this repo
        - fill in custom fields -- priority, size, hours -- to match this issue

        Once your ticket is complete, you may like to check it out on the example project board attached to this repo.
        This is so you understand how trainees will use your work.
