name: PD Coursework
description: Assign a piece of PD coursework
title: "[PD] <title>"
labels: [PD, 🏝 Priority Stretch, 🐇 Size Small]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to assign this coursework!
  - type: input
    attributes:
      label: Link to the coursework
    validations:
      required: true
  - type: input
    attributes:
      label: Estimated time in hours (PD has max 4 per week total)
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the purpose of this assignment?
      description: Clearly explain the purpose of this assignment and how trainees can evaluate this.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to submit
      description: State in clear steps how a trainee can submit this assignment.
      placeholder: |
        Copy the Google doc to your own Google Drive
        Complete the work assigned
        When you are ready, move your document to your class Drive
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give more context

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: markdown
  - type: markdown
    attributes:
      value: |
        **Thank you so much.**
        Agora, por favor, conclua este ticket preenchendo as opções na barra lateral:
	1. Atualize os rótulos (labels)
	- Prioridade – este item é essencial, obrigatório ou opcional?
	- Tamanho – ajude os participantes a planejarem seu tempo com uma estimativa aproximada
      	
       2. Adicione a um marco (milestone)
      	- Semana 1, 2, 3 ou 4
	
 	3. Adicione ao backlog do projeto
	- adicione ao projeto com o mesmo nome deste repositório
	- preencha os campos personalizados – prioridade, tamanho, horas – conforme esta issue
        -> Depois que o ticket estiver completo, você pode visualizá-lo no quadro de projeto de exemplo vinculado a este repositório. Isso ajudará você a entender como os participantes utilizarão seu trabalho.
