name: Atividade
description: Atribua o Trabalho
title: "[AT]- "
labels: "[Prioridade: ]"
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reservar um tempo para atribuir este trabalho!
  - type: input
    attributes:
      label: Link
    validations:
      required: true
  - type: input
    attributes:
      label: Tempo estimado em horas:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Qual é o objetivo desta tarefa?
      description: Explique claramente o propósito desta tarefa e como será avaliado.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Como enviar
      description: Explique em etapas claras como pode ser enviada esta tarefa.
      placeholder: |
        1: 
        2: 
        3:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Outras Informações:
      description: |
        Possui links, referências ou outros materiais que ajudem a entender melhor o contexto?
        Você pode anexar imagens, logs ou qualquer outro arquivo relevante clicando nesta área ou arrastando os arquivos diretamente aqui.
  - type: markdown
    attributes:
      value: |
        **Thank you so much.**
        Agora, por favor, conclua este ticket preenchendo as opções na barra lateral:
	1. Atualize os rótulos (labels)
	- Prioridade – este item é essencial, obrigatório ou opcional?
	- Tamanho – ajude os participantes a planejarem seu tempo com uma estimativa aproximada
      	
       2. Adicione a um marco (milestone)
      	- Semana 1, 2, 3 ou 4
	
 	3. Adicione ao backlog do projeto
	- adicione ao projeto com o mesmo nome deste repositório
	- preencha os campos personalizados – prioridade, tamanho, horas – conforme esta issue
        -> Depois que o ticket estiver completo, você pode visualizá-lo no quadro de projeto de exemplo vinculado a este repositório. Isso ajudará você a entender como os participantes utilizarão seu trabalho.
