name: Atividade Técnica
description: Atribua uma atividade técnica
title: "[TECH] <título>"
labels: ["Atividade Técnica", "📌 Prioridade Obrigatória", "📦 Tamanho Médio"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por dedicar seu tempo para atribuir esta atividade técnica!

        Para apoiar nossos participantes no planejamento e priorização da própria jornada de aprendizado, queremos que nossas atividades sejam mais informativas.
        Ou seja, não apenas dizer o que fazer, mas também explicar:
        - por que estamos fazendo isso
        - para que serve (resolução de problemas, depuração, etc.)
        - quanto tempo devem dedicar (tempo máximo)
        - como pedir ajuda
        - como revisar com respostas ou materiais
        - como obter revisão de mentores e colegas
  - type: input
    attributes:
      label: Link da atividade
      description: Informe o link relacionado a esta atividade técnica.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Por que estamos fazendo isso?
      description: Explique claramente o propósito pedagógico desta atividade.
    validations:
      required: true
  - type: input
    attributes:
      label: Tempo máximo estimado (em horas)
      description: Máximo recomendado: 16 horas por semana.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Como pedir ajuda
      description: Explique como os participantes podem obter ajuda durante a atividade.
      placeholder: |
        Compartilhe suas dúvidas no canal da turma
        Consulte: https://syllabus.codeyourfuture.io/guides/asking-questions
    validations:
      required: false
  - type: textarea
    attributes:
      label: Como enviar
      description: Explique em etapas como deve ser feita a entrega da atividade.
      placeholder: |
        Faça fork do repositório no seu GitHub
        Realize commits frequentes com mensagens claras
        Ao finalizar, abra um Pull Request para o repositório principal
        Preencha o template de PR corretamente
    validations:
      required: true
  - type: textarea
    attributes:
      label: Como revisar
      description: Informe como revisar o próprio código e como receber feedback de colegas ou mentores.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Outras informações
      description: |
        Possui links, referências ou outros materiais que ajudem a entender melhor o contexto?
        Dica: você pode anexar imagens ou arquivos arrastando-os para esta área.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        **Muito obrigado.**

        Agora, por favor, conclua este ticket preenchendo as opções na barra lateral:

        1. Atualize os rótulos (labels)
        - Prioridade – esta atividade é essencial, obrigatória ou complementar?
        - Tamanho – ajude os participantes a estimar o esforço necessário
        - Tópicos – adicione os temas relevantes

        2. Adicione a um marco (milestone)
        - Semana 1, 2, 3 ou 4

        Após finalizar este ticket, você pode adicioná-lo ao quadro de projeto de exemplo vinculado a este repositório.
        Isso ajudará a visualizar como os participantes utilizarão esta atividade. Ainda não temos automação para isso, então será feito manualmente.
