name: Atividade Extra
description: Atribua uma atividade técnica
title: "[AE]"
labels: [Prioridade, "Mandatoria", " Urgente"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por dedicar seu tempo para atribuir esta atividade!

        Para apoiar nossos participantes no planejamento e priorização da própria jornada de aprendizado, queremos que as atribuições sejam mais informativas.
        Não queremos apenas dizer o que fazer, mas também incluir informações como:
        - por que estamos fazendo isso
        - para que serve (resolução de problemas, depuração, etc.)
        - quanto tempo máximo deve ser dedicado
        - como obter ajuda
        - como revisar a atividade com base nas respostas
        - como obter revisão de mentores e colegas
  - type: input
    attributes:
      label: Link to the coursework
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why are we doing this?
      description: Explique claramente o propósito desta atividade
    validations:
      required: true
  - type: input
    attributes:
      label: "Maximum time in hours (Tech has max 16 per week total)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to get help
      description: Indique de forma simples como o participante pode obter ajuda
      placeholder: |
        Compartilhe suas dificuldades no canal da turma
        https://syllabus.codeyourfuture.io/guides/asking-questions
  - type: textarea
    attributes:
      label: How to submit
      description: Explique em etapas como enviar esta atividade
      placeholder: |
        Faça fork do repositório para sua conta do GitHub
        Realize commits pequenos e frequentes com mensagens claras
        Quando estiver pronto, abra um Pull Request no repositório da CYF
        Certifique-se de preencher o modelo de PR fornecido
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to review
      description: Como revisar o código e realizar autoavaliação
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? Referências? Qualquer informação que ajude a dar mais contexto.

        Dica: Você pode anexar imagens ou arquivos de log clicando nesta área e arrastando os arquivos para cá.
  - type: markdown
    attributes:
      value: |
        **Muito obrigado.**

        Agora, por favor, conclua este ticket preenchendo as opções na barra lateral:

        1. Atualize os rótulos (labels)
        - priority -- esta atividade é essencial, obrigatória ou complementar? Escolha uma.
        - size -- ajude os participantes a estimarem o tempo aproximado necessário. Escolha uma.
        - topics -- adicione todos os temas que considerar relevantes.
        
        2. Adicione a um marco (milestone)
        - semana 1, 2, 3 ou 4

        Após finalizar, você pode adicionar este ticket ao quadro de projeto vinculado a este repositório.
        Isso ajudará a entender como os participantes usarão esta atividade. Ainda não há automação para isso, então o processo será manual.
